# Generated by Django 4.2.16 on 2024-09-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('hla_a', models.CharField(max_length=10)),
                ('hla_b', models.CharField(max_length=10)),
                ('hla_c', models.CharField(max_length=10)),
                ('hla_drb1', models.CharField(max_length=10)),
            ],
        ),
    ]
